### ISSUE TITLE
Hi, your projz client always response error

### ISSUE THREAD

**Issue by ldnvnbl** [Slimakoi/ProjZ.py#2]

**Comment by ldnvnbl** [comment]
I received 'Unsupported Service. Please check if the app has been updated to the latest version.' error, can you resolve this problem, I want write a robot of projZ app, thank you.

**Comment by wzc-Seer** [comment]
Hi! We are aware that this happens but we are currently working on a fix for this issue, please be patient.

**Comment by ldnvnbl** [comment]
Hi, any update ?

**Comment by wzc-Seer** [comment]
Still not fixed.
